version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${username}
      - POSTGRES_PASSWORD=${password}
      - POSTGRES_DB=${database}
    ports:
      - 5432:5432
  python-app:
    image: python
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - db
    command: bash -c " pip3 install -r requirements.txt; python3 main.py"
